---
# This role contains common plays that will run on all nodes.

- name: Install python bindings for SE Linux
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - libselinux-python
   - libsemanage-python

#- name: Create the repository for EPEL
#  copy:
#    src: epel.repo
#    dest: /etc/yum.repos.d/epel.repo
#
#- name: Create the GPG key for EPEL
#  copy:
#    src: RPM-GPG-KEY-EPEL-6
#    dest: /etc/pki/rpm-gpg

- name: remove any previous ec2 rhel7 repo for nagios
  become: yes
  yum_repository:
    name: epel
    state: absent

- name: enable ec2 rhel7 repo for nagios
  become: yes
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch
    metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
     

- name: install some useful nagios plugins
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - nagios-nrpe
   - nagios-plugins-swap
   - nagios-plugins-users
   - nagios-plugins-procs
   - nagios-plugins-load
   - nagios-plugins-disk

- name: Install ntp
  become: yes
  yum:
    name: ntp
    state: present
  tags: ntp

- name: Configure ntp file
  become: yes
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  become: yes
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: ntp

# work around RHEL 7, for now
- name: insert iptables template
  become: yes
  template:
    src: iptables.j2
    dest: /etc/sysconfig/iptables
  when: ansible_distribution_major_version != '7'
  notify: restart iptables

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
